import { StyleSheet, ToastAndroid } from 'react-native';
import { colors, fontFamily, fonts } from '../../services';
import { height, totalSize, width } from 'react-native-dimension';

export const styles = StyleSheet.create({
    wrapper: {
        backgroundColor: 'rgba(127, 127, 127, 0.5)',
        flex: 1,
    },
    rowWrapper: {
        borderWidth: 1,
    },
    textInput: {
        borderWidth: 1,
    },
    headingTitle: {
        fontSize: totalSize(1.8),
        fontFamily: fontFamily.appTextBold,
        justifyContent: 'center',
        alignSelf: 'center',
        color: colors.placeholderColor,
    },
    incomeType: {
        fontSize: totalSize(1),
        color: colors.lightGreen,
        textAlign: 'center',
        fontFamily: fontFamily.appTextBold,
    },
    incomeTitle: {
        fontSize: totalSize(1.5),
        color: colors.placeholderColor,
        textAlign: 'center',
        fontFamily: fontFamily.appTextBold,
    },
    iconTextInput: {
        width: width(88)
    },
    absoluteText: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: height(3)
    },
    skipText: {
        fontSize: totalSize(1.5),
        color: colors.placeholderColor,
        textAlign: 'center',
        fontFamily: fontFamily.appTextBold,
    },
    bottomView: {
        marginBottom: height(10)
    },
    container: {
        width: '100%',
    },
    item: {
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#fff',
    },
    txt: {
        color: '#fff',
        letterSpacing: 1
    },
    btnContainer: {
        height: '100%',
        position: 'absolute',
        flexDirection: 'row'
    },
    btn: {
        height: '100%',
        backgroundColor: colors.textColor,
        alignSelf: 'center',
        alignItems: 'center',
        justifyContent: 'center'
    },
    expenseDetail: {
        fontSize: totalSize(1.3),
        color: colors.placeholderColor,
        fontFamily: fontFamily.appTextRegular,
    },
    iconStyle: {
        justifyContent: 'center',
        alignItems: 'center'
    },
    carryOverView: {
        flexDirection: "row",
        justifyContent: 'flex-start'
    },
    overviewDate: {
        fontSize: totalSize(1.6),
        fontFamily: fontFamily.appTextBold,
        color: colors.dodgerBlue,
        justifyContent: 'center',
        textAlign: 'center'
    },
    progressChartView: {
        position: 'absolute',
        left: 0,
        right: 0,
        marginTop: height(21)
    },
    progressChartText: {
        fontSize: totalSize(2),
        fontFamily: fontFamily.appTextBold,
        color: colors.textColor,
        justifyContent: 'center',
        textAlign: 'center'
    },
    forwardArrow: {
        justifyContent: 'center',
        alignSelf: 'center',
        alignItems: 'center',
        marginHorizontal: width(2)
    },
    titleText: {
        fontSize: totalSize(1.6),
        fontFamily: fontFamily.appTextBold,
        color: colors.placeholderColor,
    },
    slider: {
        width: width(100),
        height: height(5),
        marginHorizontal: -width(3)
    },
    progressBarAmountView: {
        marginTop: '-3%'
    },
    progressBarAmount: {
        fontSize: totalSize(1.4),
        fontFamily: fontFamily.appTextRegular,
        color: colors.placeholderColor,
    },
    absoluteCurrentAmount: {
        fontSize: totalSize(1.1),
        fontFamily: fontFamily.appTextBold,
        color: colors.textColor,
        marginTop: -width(7)
    },
    absoluteProjectedAmount: {
        fontSize: totalSize(1.1),
        fontFamily: fontFamily.appTextBold,
        color: colors.textColor,
        textAlign: 'right',
    },
    debtsView: {
        borderRadius: 100,
        padding: 12,
        alignItems: 'center',
    },
    projectedText: {
        fontSize: totalSize(1.6),
        fontFamily: fontFamily.appTextBold,
        color: colors.placeholderColor,
    },
    projectedTextType: {
        fontSize: totalSize(1.3),
        fontFamily: fontFamily.appTextBold,
        color: '#007FFF',
    },
    absoluteCurrentAmountDebt: {
        fontSize: totalSize(1.1),
        fontFamily: fontFamily.appTextBold,
        color: colors.textColor,
        textAlign: 'right',
        marginTop: -width(7)
    },
    absoluteProjectedAmountDebt: {
        fontSize: totalSize(1.1),
        fontFamily: fontFamily.appTextBold,
        color: colors.textColor,
    },
    iconView: {
        backgroundColor: colors.textColor,
        // padding: 15,
        width: totalSize(5),
        height: totalSize(5),
        borderRadius: 100,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: width(2)
    },
    notification: {
        fontSize: totalSize(1.8),
        color: colors.black,
        fontFamily: fontFamily.appTextRegular,
    },
    time: {
        fontSize: totalSize(1.1),
        color: colors.black,
        fontFamily: fontFamily.appTextRegular,
    },
    textWrapper: {
        justifyContent: 'center',
        flex: 1,
    },
    // tooltips
    popupText: {
        color: colors.white,
        fontSize: totalSize(1.6),
        fontFamily: fontFamily.appTextBold,
        padding: 20,
        textAlign: 'center',
        zIndex: 1,
    },
    popupPoint: {
        position: 'absolute',
        backgroundColor: colors.white,
        right: width(15),
        width: totalSize(8),
        height: totalSize(8),
        borderRadius: 100,
        top: 5
    },
    popup: {
        backgroundColor: 'rgb(35, 105, 93)',
        position: 'absolute',
        marginTop: -totalSize(8),
        borderRadius: 5,
        width: width(50),
        alignSelf: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.white,
        zIndex: 1,
    },
    popupPointAutoFill: {
        position: 'absolute',
        backgroundColor: colors.white,
        left: -width(1),
        width: totalSize(14),
        height: totalSize(14),
        marginTop: -totalSize(2),
        borderRadius: 100,
        top: 5
    },
    popupAutoFill: {
        position: 'absolute',
        marginTop: -totalSize(14),
        backgroundColor: 'rgb(35, 105, 93)',
        borderRadius: 5,
        width: width(80),
        alignSelf: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.white,
        zIndex: 1,
    },
    popupMinimum: {
        backgroundColor: 'rgb(35, 105, 93)',
        position: 'absolute',
        marginTop: -totalSize(16),
        borderRadius: 5,
        width: width(80),
        alignSelf: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.white,
        zIndex: 1,
    },
    popupPointMinimum: {
        position: 'absolute',
        backgroundColor: colors.white,
        right: width(15),
        width: totalSize(8),
        height: totalSize(8),
        borderRadius: 100,
        top: 5
    },
    popupSource: {
        position: 'absolute',
        marginTop: -totalSize(12),
        backgroundColor: 'rgb(35, 105, 93)',
        borderRadius: 5,
        width: width(50),
        alignSelf: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.white,
        zIndex: 1,
    },
    popupPointSource: {
        position: 'absolute',
        backgroundColor: colors.white,
        left: -width(1),
        marginTop: -totalSize(3),
        width: totalSize(12),
        height: totalSize(12),
        borderRadius: 100,
        top: 5
    },
    popupType: {
        position: 'absolute',
        marginTop: -totalSize(15),
        backgroundColor: 'rgb(35, 105, 93)',
        borderRadius: 5,
        width: width(80),
        alignSelf: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.white,
        zIndex: 1,
    },
    popupPointFrequency: {
        position: 'absolute',
        backgroundColor: colors.white,
        left: -width(1),
        marginTop: -totalSize(1),
        width: totalSize(9),
        height: totalSize(9),
        borderRadius: 100,
        top: 5
    },
    popupNextDate: {
        position: 'absolute',
        marginTop: -totalSize(13),
        backgroundColor: 'rgb(35, 105, 93)',
        borderRadius: 5,
        width: width(80),
        alignSelf: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.white,
        zIndex: 1,
    },
    popupDebtsModal: {
        position: 'absolute',
        marginTop: -totalSize(14),
        left: 0,
        backgroundColor: 'rgb(35, 105, 93)',
        borderRadius: 5,
        width: width(80),
        alignSelf: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.white,
        zIndex: 1,
    },
    popupDebtsModal1: {
        position: 'absolute',
        marginTop: -totalSize(7),
        right: width(6),
        backgroundColor: 'rgb(35, 105, 93)',
        borderRadius: 5,
        width: width(80),
        alignSelf: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.white,
        zIndex: 1,
    },
    popupPointExpense: {
        position: 'absolute',
        backgroundColor: colors.white,
        left: -totalSize(1),
        marginTop: -totalSize(0.3),
        width: totalSize(5),
        height: totalSize(5),
        borderRadius: 100,
    },
    popupExpense: {
        backgroundColor: 'rgb(35, 105, 93)',
        position: 'absolute',
        marginTop: -totalSize(5),
        left: totalSize(6),
        borderRadius: 5,
        width: width(50),
        alignSelf: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.white,
        zIndex: 1,
    },
    popupPointBill: {
        position: 'absolute',
        backgroundColor: colors.white,
        left: -totalSize(1),
        marginTop: -totalSize(0.3),
        width: totalSize(8),
        height: totalSize(8),
        borderRadius: 100,
    },
    popupBill: {
        backgroundColor: 'rgb(35, 105, 93)',
        position: 'absolute',
        marginTop: -totalSize(8),
        left: totalSize(6),
        borderRadius: 5,
        width: width(50),
        alignSelf: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.white,
        zIndex: 1,
    },
    popupPointHeaderExpense: {
        backgroundColor: colors.white,
        alignItems: 'center',
        justifyContent: 'center',
        left: width(2),
        // marginTop: -totalSize(0.3),
        width: totalSize(5),
        height: totalSize(5),
        borderRadius: 100,
    },
    tooltipValueText: {
        alignSelf: 'center',
        position: 'absolute',
    },
    popupHeaderExpense: {
        backgroundColor: 'rgb(35, 105, 93)',
        position: 'absolute',
        marginTop: totalSize(1),
        // marginLeft: 0,
        zIndex: 1,
        left: 10,
        borderRadius: 5,
        width: width(50),
        alignSelf: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.white,
    },
    popupPointDetail: {
        backgroundColor: colors.white,
        position: 'absolute',
        right: totalSize(3),
        width: totalSize(6),
        height: totalSize(6),
        borderRadius: 100,
    },
    popupDetail: {
        backgroundColor: 'rgb(35, 105, 93)',
        position: 'absolute',
        zIndex: 1,
        top: totalSize(6),
        borderRadius: 5,
        width: width(50),
        alignSelf: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.white,
    },
    popupPointEditAble: {
        backgroundColor: colors.white,
        position: 'absolute',
        left: 0,
        width: totalSize(5),
        height: totalSize(5),
        borderRadius: 100,
    },
    popupEditAble: {
        backgroundColor: 'rgb(35, 105, 93)',
        position: 'absolute',
        zIndex: 1,
        borderRadius: 5,
        width: width(80),
        alignSelf: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.white,
    },
    popupPointEditAble1: {
        backgroundColor: colors.white,
        position: 'absolute',
        right: 0,
        width: totalSize(5),
        height: totalSize(5),
        borderRadius: 100,
    },
    popupEditAble1: {
        backgroundColor: 'rgb(35, 105, 93)',
        position: 'absolute',
        left: width(5),
        zIndex: 1,
        borderRadius: 5,
        width: width(75),
        alignSelf: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.white,
    },
    popupHomeDots: {
        backgroundColor: 'rgb(35, 105, 93)',
        position: 'absolute',
        // left: width(5),
        zIndex: 1,
        borderRadius: 5,
        width: width(75),
        alignSelf: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.white,
    },
    popupPointHomeDots: {
        backgroundColor: colors.white,
        position: 'absolute',
        left: -width(3),
        width: totalSize(5),
        height: totalSize(5),
        borderRadius: 100,
        justifyContent: 'center',
        alignSelf: 'center'
    },
    popupPointHomeName: {
        backgroundColor: colors.white,
        position: 'absolute',
        left: width(32.5),
        right: 0,
        top: 0,
        bottom: 0,
        justifyContent: 'center',
        alignSelf: 'center',
        alignItems: 'center',
        width: width(25),
        height: width(25),
        borderRadius: 100,
    },
    popupPointHomePlus: {
        backgroundColor: colors.white,
        position: 'absolute',
        right: width(8),
        justifyContent: 'center',
        alignSelf: 'center',
        alignItems: 'center',
        width: totalSize(5),
        height: totalSize(5),
        borderRadius: 100,
    },
    popupPointHomeUser: {
        backgroundColor: colors.white,
        position: 'absolute',
        right: -width(2),
        justifyContent: 'center',
        alignSelf: 'center',
        alignItems: 'center',
        width: totalSize(5),
        height: totalSize(5),
        borderRadius: 100,
    },
    popupPointEditExp: {
        backgroundColor: colors.white,
        position: 'absolute',
        right: 0,
        justifyContent: 'center',
        alignSelf: 'center',
        alignItems: 'center',
        width: totalSize(5),
        height: totalSize(5),
        borderRadius: 100,
    },
    popupEditExp: {
        backgroundColor: 'rgb(35, 105, 93)',
        position: 'absolute',
        top: totalSize(5),
        right: totalSize(5),
        zIndex: 1,
        borderRadius: 5,
        width: width(45),
        alignSelf: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.white,
    },
    popupPointSave1: {
        backgroundColor: 'rgb(35, 105, 93)',
        position: 'absolute',
        top: -width(25),
        left: width(25),
        zIndex: 1,
        borderRadius: 5,
        width: width(45),
        alignSelf: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.white,
    },
    popupPointSave: {
        backgroundColor: colors.white,
        position: 'absolute',
        top: -totalSize(1),
        left: width(45),
        justifyContent: 'center',
        alignSelf: 'center',
        alignItems: 'center',
        width: width(15),
        height: width(15),
        borderRadius: 100,
    },
    popupPointCarry: {
        backgroundColor: colors.white,
        position: 'absolute',
        top: -totalSize(1),
        left: totalSize(1),
        justifyContent: 'center',
        alignSelf: 'center',
        alignItems: 'center',
        width: width(15),
        height: width(15),
        borderRadius: 100,
    },
    popupPointSave2: {
        backgroundColor: 'rgb(35, 105, 93)',
        position: 'absolute',
        top: -width(25),
        left: width(5),
        zIndex: 1,
        borderRadius: 5,
        width: width(80),
        alignSelf: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.white,
    },
    popupPointDebts: {
        backgroundColor: colors.white,
        position: 'absolute',
        top: -width(3),
        left: width(30),
        justifyContent: 'center',
        alignSelf: 'center',
        alignItems: 'center',
        width: width(40),
        height: width(40),
        borderRadius: 100,
    },
    popupDebts: {
        backgroundColor: 'rgb(35, 105, 93)',
        position: 'absolute',
        top: -width(20),
        zIndex: 1,
        borderRadius: 5,
        width: width(80),
        alignSelf: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.white,
    },
    popupPointDebts1: {
        backgroundColor: colors.white,
        position: 'absolute',
        top: -width(3),
        right: -width(10),
        justifyContent: 'center',
        alignSelf: 'center',
        alignItems: 'center',
        width: width(40),
        height: width(40),
        borderRadius: 100,
    },
    popupDebts1: {
        backgroundColor: 'rgb(35, 105, 93)',
        position: 'absolute',
        top: -width(40),
        zIndex: 1,
        borderRadius: 5,
        width: width(90),
        alignSelf: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.white,
    },
    popupInsightDots: {
        backgroundColor: 'rgb(35, 105, 93)',
        position: 'absolute',
        left: width(5),
        zIndex: 1,
        borderRadius: 5,
        width: width(75),
        alignSelf: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.white,
    },
    popupPointDate: {
        backgroundColor: colors.white,
        position: 'absolute',
        top: -width(7),
        left: width(37),
        right: 0,
        width: width(20),
        height: width(20),
        borderRadius: 100,
    },
    popupInsightDate: {
        backgroundColor: 'rgb(35, 105, 93)',
        position: 'absolute',
        left: width(6),
        right: 0,
        top: width(17),
        zIndex: 1,
        borderRadius: 5,
        width: width(82),
        justifyContent: 'center',
        alignSelf: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.white,
    },
    popupPointDetailExpense: {
        backgroundColor: colors.white,
        position: 'absolute',
        top: width(15),
        left: width(32),
        right: 0,
        width: width(30),
        height: width(30),
        borderRadius: 100,
    },
    popupDetailExpense: {
        backgroundColor: 'rgb(35, 105, 93)',
        position: 'absolute',
        left: width(6),
        right: 0,
        top: 0,
        zIndex: 1,
        borderRadius: 5,
        width: width(82),
        justifyContent: 'center',
        alignSelf: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.white,
    },
    popupPointTotalDebts: {
        backgroundColor: colors.white,
        position: 'absolute',
        top: -width(5),
        right: 0,
        width: width(20),
        height: width(20),
        borderRadius: 100,
    },
    popupTotalDebts: {
        backgroundColor: 'rgb(35, 105, 93)',
        position: 'absolute',
        right: 0,
        top: 0,
        zIndex: 1,
        borderRadius: 5,
        width: width(82),
        justifyContent: 'center',
        alignSelf: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.white,
    },
    popupPointPayoff: {
        backgroundColor: colors.white,
        position: 'absolute',
        top: -width(5),
        right: 0,
        width: width(15),
        height: width(15),
        borderRadius: 100,
    },
    popupPayoff: {
        backgroundColor: 'rgb(35, 105, 93)',
        position: 'absolute',
        right: width(3),
        top: 0,
        zIndex: 1,
        borderRadius: 5,
        width: width(82),
        justifyContent: 'center',
        alignSelf: 'center',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.white,
    },
    popupPointNoti: {
        backgroundColor: colors.white,
        position: 'absolute',
        right: width(5),
        top: width(1),
        width: width(15),
        height: width(15),
        borderRadius: 100,
    },
});
